### PR TITLE
use a seperate k8s secret for extension

### PR DESCRIPTION
**Pull request by blairdrummond**
I'd do it like this, using a separate secret and {{ if enabled }} logic.

I'll give you my kind template to test this tomorrow.

### CODE REVIEW

**Comment by blairdrummond** [comment]
Note, I haven't tested this yet, so might not be free of syntax errors yet

**Comment by blairdrummond** [comment]
[ckan-kind.zip](https://github.com/Locutus66/charts/files/6709644/ckan-kind.zip)

Hey @Locutus66 , take a look at this. You can message me in the chat, but this should give you most of what you need to test ckan in kubernetes locally in your VM, including updates to the helm chart

**Comment by Locutus66** [comment]
Yep, this looks good.

**Review by Locutus66 — COMMENTED** [review]
Looks good.

**Pull request merged**
